name: app
description: "Um desafio técnico desenvolvido como parte do processo seletivo da Target Sistemas"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.6.0
  flutter_mobx: ^2.3.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.4
  remixicon: ^4.9.3
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  provider: ^6.1.5+1
  flutter_spinkit: ^5.2.2
  fl_chart: ^1.2.0
  cloud_firestore: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mobx_codegen: ^2.7.7
  build_runner: ^2.13.1
  launcher_name: ^1.0.2

launcher_name:
  default: "Target Challenge"


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
